<?php
/**
 * Class for manipulating rendered HTML output.
 *
 * @package GatherPressMagicMenu
 */

namespace GatherPress_Magic_Menu;

use GatherPress\Core;

if ( ! class_exists( 'HTML_Processor' ) ) {
	/**
	 * Singleton class for manipulating rendered HTML output.
	 *
	 * Responsibilities:
	 * - Apply wrapper attributes to rendered blocks
	 * - Add disabled attributes and classes
	 * - Apply overlay colors to submenu containers
	 * - Add interaction classes to submenu items
	 *
	 * @since 0.1.0
	 */
	class HTML_Processor {

		use Core\Traits\Singleton;

		/**
		 * Private constructor to prevent direct instantiation.
		 *
		 * @since 0.1.0
		 */
		private function __construct() {}

		/**
		 * Applies wrapper attributes to the rendered HTML.
		 *
		 * Uses the HTML Processor API to merge wrapper attributes
		 * (including theme.json styles and block style classes) into
		 * the rendered output.
		 *
		 * @since 0.1.0
		 * @param string $html                The rendered HTML.
		 * @param string $wrapper_attributes  Wrapper attributes from get_block_wrapper_attributes().
		 * @return string The modified HTML with wrapper attributes applied.
		 */
		public function apply_wrapper_attributes( string $html, string $wrapper_attributes ): string {
			if ( empty( $wrapper_attributes ) ) {
				return $html;
			}

			$processor = new \WP_HTML_Tag_Processor( $html );

			if ( ! $processor->next_tag( array( 'tag_name' => 'li' ) ) ) {
				return $html;
			}

			preg_match( '/class="([^"]*)"/', $wrapper_attributes, $class_matches );
			preg_match( '/style="([^"]*)"/', $wrapper_attributes, $style_matches );

			if ( ! empty( $class_matches[1] ) ) {
				$wrapper_classes = explode( ' ', $class_matches[1] );
				foreach ( $wrapper_classes as $class ) {
					if ( ! empty( $class ) ) {
						$processor->add_class( $class );
					}
				}
			}

			if ( ! empty( $style_matches[1] ) ) {
				$existing_style = $processor->get_attribute( 'style' );
				$new_style      = $existing_style ? $existing_style . '; ' . $style_matches[1] : $style_matches[1];
				$processor->set_attribute( 'style', $new_style );
			}

			return $processor->get_updated_html();
		}

		/**
		 * Adds disabled attributes to the rendered HTML using the HTML Processor API.
		 *
		 * @since 0.1.0
		 * @param string $html The rendered HTML.
		 * @return string The modified HTML with aria-disabled and class added.
		 */
		public function add_disabled_attributes( string $html ): string {
			$html = $this->add_aria_disabled_to_link( $html );
			$html = $this->add_disabled_class_to_list_item( $html );
			return $html;
		}

		/**
		 * Applies container attributes (class and style) to the <ul> element.
		 *
		 * Uses the HTML Processor API to add the color classes and inline styles
		 * generated by wp_apply_colors_support() to the submenu container.
		 *
		 * @since 0.1.0
		 * @param string                $html                    The rendered HTML.
		 * @param array<string, string> $container_attributes   Array with 'class' and 'style' keys.
		 * @return string The modified HTML.
		 */
		public function apply_container_attributes_to_ul( string $html, array $container_attributes ): string {
			$processor = new \WP_HTML_Tag_Processor( $html );

			// Find the <ul> with class wp-block-navigation__submenu-container.
			if ( $processor->next_tag(
				array(
					'tag_name'   => 'ul',
					'class_name' => 'wp-block-navigation__submenu-container',
				)
			) ) {
				// Add color classes.
				if ( ! empty( $container_attributes['class'] ) ) {
					$classes = explode( ' ', $container_attributes['class'] );
					foreach ( $classes as $class ) {
						if ( ! empty( $class ) ) {
							$processor->add_class( $class );
						}
					}
				}

				// Add or merge inline styles.
				if ( ! empty( $container_attributes['style'] ) ) {
					$existing_style = $processor->get_attribute( 'style' );
					$new_style      = $existing_style ? $existing_style . '; ' . $container_attributes['style'] : $container_attributes['style'];
					$processor->set_attribute( 'style', $new_style );
				}
			}

			return $processor->get_updated_html();
		}

		/**
		 * Applies interaction classes to the submenu <li> element.
		 *
		 * Adds classes like 'open-on-click' and 'open-on-hover-click' to control
		 * submenu interaction behavior.
		 *
		 * @since 0.1.0
		 * @param string             $html    The rendered HTML.
		 * @param array<int, string> $classes Array of classes to add.
		 * @return string The modified HTML.
		 */
		public function apply_interaction_classes_to_li( string $html, array $classes ): string {
			if ( empty( $classes ) ) {
				return $html;
			}

			$processor = new \WP_HTML_Tag_Processor( $html );

			if ( $processor->next_tag(
				array(
					'tag_name'   => 'li',
					'class_name' => 'wp-block-navigation-item',
				)
			) ) {
				foreach ( $classes as $class ) {
					if ( ! empty( $class ) ) {
						$processor->add_class( $class );
					}
				}
			}

			return $processor->get_updated_html();
		}

		/**
		 * Builds interaction classes for submenu items.
		 *
		 * Mimics core/navigation-submenu's behavior for controlling
		 * how submenus open (on click vs hover+click).
		 *
		 * @since 0.1.0
		 * @param array<string, mixed> $nav_context Navigation context.
		 * @return array<int, string> Array of CSS classes.
		 */
		public function get_submenu_interaction_classes( array $nav_context ): array {
			$show_submenu_indicators = isset( $nav_context['showSubmenuIcon'] ) && $nav_context['showSubmenuIcon'];
			$open_on_click           = isset( $nav_context['openSubmenusOnClick'] ) && $nav_context['openSubmenusOnClick'];
			$open_on_hover_and_click = isset( $nav_context['openSubmenusOnClick'] ) && ! $nav_context['openSubmenusOnClick'] && $show_submenu_indicators;

			$classes = array();

			if ( $open_on_click ) {
				$classes[] = 'open-on-click';
			}

			if ( $open_on_hover_and_click ) {
				$classes[] = 'open-on-hover-click';
			}

			return $classes;
		}

		/**
		 * Adds aria-disabled attribute to the anchor tag.
		 *
		 * @since 0.1.0
		 * @param string $html The rendered HTML.
		 * @return string The modified HTML.
		 */
		private function add_aria_disabled_to_link( string $html ): string {
			$processor = new \WP_HTML_Tag_Processor( $html );

			if ( $processor->next_tag(
				array(
					'tag_name'   => 'a',
					'class_name' => 'wp-block-navigation-item__content',
				)
			) ) {
				$processor->set_attribute( 'aria-disabled', 'true' );
				$processor->set_attribute( 'aria-label', __( 'No upcoming events available', 'gatherpress-magic-menu' ) );

			}

			return $processor->get_updated_html();
		}

		/**
		 * Adds disabled BEM modifier class to the list item.
		 *
		 * Uses .gatherpress-magic-menu--disabled as the BEM modifier.
		 *
		 * @since 0.1.0
		 * @param string $html The rendered HTML.
		 * @return string The modified HTML.
		 */
		private function add_disabled_class_to_list_item( string $html ): string {
			$processor = new \WP_HTML_Tag_Processor( $html );

			if ( $processor->next_tag(
				array(
					'tag_name'   => 'li',
					'class_name' => 'wp-block-navigation-item',
				)
			) ) {
				$processor->add_class( 'gatherpress-magic-menu--disabled' );
			}

			return $processor->get_updated_html();
		}
	}
}
